complete -c funcevents -xa "(functions -na)" --description "Show function notification subscriptions"
complete -c funcevents -s e -l on-event -x --description "Notify when event fires"
complete -c funcevents -s s -l on-signal -x --description "Notify when signal raised"
complete -c funcevents -s v -l on-variable -x --description "Notify when variable changed"
complete -c funcevents -s p -l on-process-exit -x -a "(__fish_complete_pids)" --description "Notify when process ends"
complete -c funcevents -s j -l on-job-exit --description "Notify when job completes"
complete -c funcevents -s r -l remove --description "Unregister function from notifications"
complete -c funcevents -s h -l help --description "Display help and exit"

complete -c funcevents -n "__fish_contains_opt -s r" -xa "(functions -na)" --description "Unsubscribe function from notification"
complete -c funcevents -n "__fish_contains_opt -s r" -s e -l on-event -x --description "Stop notifying when event fires"
complete -c funcevents -n "__fish_contains_opt -s r" -s s -l on-signal -x --description "Stop notifying when signal raised"
complete -c funcevents -n "__fish_contains_opt -s r" -s v -l on-variable -x --description "Stop notifying when variable changed"
complete -c funcevents -n "__fish_contains_opt -s r" -s p -l on-process-exit -x -a "(__fish_complete_pids)" --description "Stop notifying when process ends"
complete -c funcevents -n "__fish_contains_opt -s r" -s j -l on-job-exit --description "Stop notifying when job completes"